apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-pvc
  labels:
    app: dokuwiki
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: nginx-data-pv
