apiVersion: v1
kind: Deployment
metdata:
  name: www-deployment
  namespace: default
  labels:
    app: dokuwiki

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dokuwiki
  template:
    metadata:
      labels:
        app: dokuwiki
    spec:
      containers:
      - image: localhost/dokuwiki-www-alpine:1.4.1
        name: www
        ports:
        - containerPorts: 80
          name: web
        volumeMounts:
        - name: nginx-conf-persistent-storage
          mountPath: /etc/nginx/conf.d
        - name: nginx-data-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: nginx-conf-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-conf-pvc
      - name: nginx-data-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-data-pvc
