apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    app: dokuwiki
spec:
  ports:
    - port: 80
  selector:
    app: dokuwiki
    tier: php
  clusterIP: None
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: php-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
    - rw
  nfs:
    server: docker01.arno-meschin.gmail.com.beta.tailscale.net
    path: "/app/dokuwiki"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    app: dokuwiki
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: php-pv
---
apiVersion: v1
kind: Deployment
metdata:
  name: dokuwiki-php-fpm
  labels:
    app: dokuwiki
spec:
  selector:
    matchLabels:
      app: dokuwiki
      tier: php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dokuwiki
        tier: php
    spec:
      containers:
      - image: localhost/dokuwiki-php-alpine:1.5
        name: www
        ports:
        - containerPorts: 9000,9001
          name: php
        volumeMounts:
        - name: php-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: php-persistent-storage
        persistentVolumeClaim:
          claimName: php-pvc